- LICENSE
This pull request changes the copyright year range to an open-ended range. The first year is the only year that matters anyway.
> legal: use open-ended copyright year range

- go.mod
- go.sum
This pull request bumps the underlying Mutagen dependency to v0.14.0.
> all: bump Mutagen version to v0.14.0

- pkg/mutagen/configuration.go
- pkg/mutagen/liaison.go
This change was discussed in Mutagen Slack. This PR adds a container_name option to the sidecar config. This allows users to give a friendlier name to the sidecar container. The friendly name can be leveraged in e.g. monitoring tools.
**Any other notes for the review process?**
There are no checks for conflicting container names. If you attempt to run mutagen-compose with conflicting container names, the mutagen sidecar and sync will start, but the docker daemon will return a conflict error for the compose project. Is this something we want to attempt to address inside mutagen-compose?
> sidecar: added container_name configuration option

- go.mod
- go.sum
- pkg/mutagen/compose.go
- pkg/mutagen/docker.go
This commit updates the underlying Compose version to v2.5.0.
In testing this update, a bug was uncovered (unrelated to the update, simply noticed due to a change in related code) in Mutagen Compose's `start` implementation that caused sessions to be terminated.  A fix is also included in this pull request.
> all: update to Compose v2.5.0 and tweak start behavior

- go.mod
- go.sum
This commit updates the underlying Mutagen version to v0.15.0-beta2.
> all: update to Mutagen v0.15.0-beta2

- go.mod
- go.sum
This commit updates the underlying Mutagen version to v0.15.0-beta3.
> all: update to Mutagen v0.15.0-beta3

- go.mod
- go.sum
This commit updates the underlying Mutagen version to v0.15.0.
> all: update to Mutagen v0.15.0

- pkg/mutagen/compose.go
- pkg/mutagen/liaison.go
This PR fixes a bug where the Mutagen sidecar service might not be started automatically on `run`.
> run: ensure sidecar service is always started on run

- scripts/ci/verify_commits.sh
This PR fixes the `verify_commits.sh` script to account for the fact that we want to allow PR merges into `main` that are not fully up-to-date.
> ci: use double dot range spec for rev-list in verify_commits.sh

- go.mod
- go.sum
This PR updates the underlying Mutagen version to v0.15.2.
> all: update to Mutagen v0.15.2

- .github/issue_template.md
- .github/pull_request_template.md
- .github/workflows/ci.yml
- go.mod
- go.sum
This PR updates Go to 1.19.1 and Mutagen to v0.16.0-beta1.
> all: update Go and Mutagen for v0.16.0-beta1

- go.mod
- go.sum
This PR updates the underlying Mutagen version to v0.16.0-beta2.
> all: update to Mutagen v0.16.0-beta2

- go.mod
- go.sum
This PR updates the underlying Mutagen version to v0.15.4.
> all: update to Mutagen v0.15.4

- go.mod
- go.sum
This PR updates the Mutagen dependency to v0.16.0.
> deps: update Mutagen to v0.16.0

- go.mod
- go.sum
This commit updates the underlying Mutagen version to v0.16.2.
> deps: update Mutagen to v0.16.2

- .github/workflows/ci.yml
This PR updates to Go toolchain to version 1.20.
Unlike previous Go toolchain updates, we're going to continue supporting (and testing) the previous Go release as well.
> deps: update to Go 1.20

- .github/workflows/ci.yml
- go.mod
- go.sum
This PR updates the Mutagen dependency to v0.16.5 and the Go toolchain to 1.19.6.
> all: prepare for v0.16.5 release

- go.mod
- go.sum
This PR updates the underlying Mutagen version to v0.17.1.
**Which issue(s) does this pull request address (if any)?**
This addresses [CVE-2023-30844](https://github.com/mutagen-io/mutagen/security/advisories/GHSA-jmp2-wc4p-wfh2) and [GHSA-fwj4-72fm-c93g](https://github.com/mutagen-io/mutagen/security/advisories/GHSA-fwj4-72fm-c93g).
> deps: update to Mutagen v0.17.1

- .github/workflows/ci.yml
- go.mod
- go.sum
This PR updates the following dependencies:
- Go to 1.20.5 and 1.19.10
- These releases contain a fix for CVE-2023-29403
- Mutagen to v0.17.2
- An incidental but important update has also occurred to the forked fsevents package used by Mutagen, which was previously colliding with the upstream package used by Docker Compose 2.17.0+.  This fix is a hack for the time being, but should be fairly robust until we can get back on the upstream fsevents package.  See mutagen-io/mutagen-compose#64 and mutagen-io/mutagen#452 for more information.
**Which issue(s) does this pull request address (if any)?**
This will help to unblock mutagen-io/mutagen-compose#64.
> deps: update Go and Mutagen

- .github/workflows/ci.yml
- go.mod
- go.sum
This PR backports updates to the following dependencies:
- Go to 1.20.5 and 1.19.10
- These releases contain a fix for CVE-2023-29403
- Mutagen to v0.17.2
- An incidental but important update has also occurred to the forked fsevents package used by Mutagen, which was previously colliding with the upstream package used by Docker Compose 2.17.0+.  This fix is a hack for the time being, but should be fairly robust until we can get back on the upstream fsevents package.  See mutagen-io/mutagen-compose#64 and mutagen-io/mutagen#452 for more information.
**Which issue(s) does this pull request address (if any)?**
This will help to unblock mutagen-io/mutagen-compose#64.
> deps: backport Go and Mutagen updates

- scripts/ci/verify_commits.sh
This PR tells the CI system to avoid validation of merge commits.  Merge commits typically won't have a sign-off or cryptographic signature, so we want to avoid failing on these if (e.g.) verifying a pull request with merge commits in it.
**Which issue(s) does this pull request address (if any)?**
#69
> ci: avoid validation of merge commits

- .github/workflows/ci.yml
- go.mod
- go.sum
This PR updates to Go 1.20.12 and Mutagen v0.17.4.
> all: prepare for v0.17.4 release
